SilverStripe\GraphQL\Controller:
  cors:
    Enabled: false
    Allow-Origin:
      - 'http://localhost:8085'
      - 'http://localhost:8145'
      - 'http://localhost:3000'
      - 'http://mitmproxy:8080'
      - '172.18.0.1'
    Allow-Headers: 'Authorization, Content-Type, Credentials, x-xsrf-token'
    Allow-Methods:  'GET, POST, OPTIONS'
    #Max-Age:  600  # 600 seconds = 10 minutes.

    #SilverStripe\GraphQL\Manager:
    #properties:
    #Middlewares:
    #HTTPMethodMiddleware: false

    #authenticators:
    #class: SilverStripe\GraphQL\Auth\BasicAuthAuthenticator
    #priority: 10
